In [5]:
import torch



In [15]:
x = torch.rand(4,3)
y=torch.rand(4,3)
print(x)
print(y)

tensor([[0.1522, 0.7610, 0.9228],
        [0.9190, 0.2340, 0.8556],
        [0.1343, 0.8774, 0.7944],
        [0.1321, 0.0413, 0.5023]])
tensor([[0.9954, 0.1664, 0.4362],
        [0.4432, 0.3103, 0.6593],
        [0.8202, 0.4467, 0.9401],
        [0.5654, 0.6659, 0.8444]])


In [17]:
print(x+y)
y.add(x)

tensor([[1.1476, 0.9274, 1.3590],
        [1.3622, 0.5443, 1.5149],
        [0.9545, 1.3241, 1.7346],
        [0.6974, 0.7073, 1.3468]])


tensor([[1.1476, 0.9274, 1.3590],
        [1.3622, 0.5443, 1.5149],
        [0.9545, 1.3241, 1.7346],
        [0.6974, 0.7073, 1.3468]])

In [17]:
x=torch.ones((2,2),requires_grad=True)
print(x)
print(x**2)
y=x.sum()
print(x.grad)
y.backward()
print(x.grad)
x.sum().backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)
None
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
